version: "3.8"
services:
  db:
    image: mysql:8.2.0
    container_name: fastapi-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogapplication
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3307:3306
    expose:
      - 3306
  api:
    build: .
    container_name: fastapi-backend
    ports:
      - 80:80
    depends_on:
      - db

volumes:
  db_data: